name: Strapi-CMS Code Deploy

on:
  push:
    branches:
      - staging

jobs:

  Strapi-CMS_Code_Deploy:

    permissions:
      contents: read
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification on Pipeline Start
        uses: act10ns/slack@v2
        with:
          status: starting
          message: Pipeline Triggered on Strapi-CMS
        if: always()


      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install doctl
        run: |
          curl -OL https://github.com/digitalocean/doctl/releases/download/v1.94.0/doctl-1.94.0-linux-amd64.tar.gz
          tar xf doctl-1.94.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin
      
      - name: Login to DO Container Registry
        run: doctl registry login --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


      - name: Get the latest commit ID
        id: get_commit_id
        run: echo "GIT_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV   
           

      - name: Build Docker image
        id: Docker-Build
        run: |
          docker build -f Dockerfile -t strapi-cms:latest .

      - name: Tag Docker image
        run: | 
          docker tag strapi-cms:latest registry.digitalocean.com/kaizen-staging/strapi-cms:latest
          docker tag strapi-cms:latest registry.digitalocean.com/kaizen-staging/strapi-cms:${{ env.GIT_COMMIT_ID }}

      - name: Push Docker image to DO Container Registry
        id: Docker-Push
        run: |
          docker push registry.digitalocean.com/kaizen-staging/strapi-cms:latest
          docker push registry.digitalocean.com/kaizen-staging/strapi-cms:${{ env.GIT_COMMIT_ID }}


      - name: Set up bash
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Jenkins script
        id: Trigger-Jenkins
        run: |
        
          #!/bin/bash

          check_pipeline_status() {
              local pipeline_status=$(curl -u jenkins-staging:${{ secrets.JENKINS_STAGING_API_TOKEN }} -s "https://jenkins-staging.kaizenprint.com/job/Strapi-Staging-Deploy/$1/api/json" | jq -r '.inProgress' 2>/dev/null)
              echo "$pipeline_status"
          }

          
          lastBuild_no=$(curl -u jenkins-staging:${{ secrets.JENKINS_STAGING_API_TOKEN }} -s https://jenkins-staging.kaizenprint.com/job/Strapi-Staging-Deploy/lastBuild/api/json | jq -r '.number')
          echo "Last Build Number: $lastBuild_no"

          currentBuild_no=$((lastBuild_no + 1))
          echo "Current Build Number: $currentBuild_no"

          curl -X POST -u jenkins-staging:${{ secrets.JENKINS_STAGING_API_TOKEN }} https://jenkins-staging.kaizenprint.com/job/Strapi-Staging-Deploy/build

          while true; do
              pipeline_status=$(check_pipeline_status "$currentBuild_no")
              if [ "$pipeline_status" == "false" ]; then
                  break
              fi
              echo "Pipeline Running"
              sleep 10 
          done

          build_status=$(curl -u jenkins-staging:${{ secrets.JENKINS_STAGING_API_TOKEN }} -s https://jenkins-staging.kaizenprint.com/job/Strapi-Staging-Deploy/$currentBuild_no/api/json | jq -r '.result')
          echo "$build_status"

          if [ "$build_status" == "FAILURE" ]; then
              echo "Build failed"
              exit 1
          fi

      - name: Slack Result Notification
        id: result
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.KAIZEN_SLACK_STAGING_WEBHOOK_URL }}